services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${STORE_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: go_server
    restart: always
    depends_on:
      - db
    environment:
      STORE_DB_URL: ${STORE_DB_URL}
    ports:
      - "8080:8080"
  
volumes:
  postgres-data: